# Generated by Django 3.2.7 on 2021-09-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20210924_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('down', 'down vote'), ('up', 'up vote')], max_length=200),
        ),
    ]
