# Generated by Django 3.2.7 on 2021-09-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20210924_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
