# Generated by Django 3.2.7 on 2021-09-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210919_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('up', 'up vote'), ('down', 'down vote')], max_length=200),
        ),
    ]
